# Generated by Django 2.1.3 on 2018-11-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumengine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
