# Generated by Django 2.1.3 on 2018-11-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumengine', '0002_auto_20181118_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
