# Generated by Django 2.1.3 on 2018-11-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumengine', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='unnamed', max_length=80)),
                ('date_of_pub', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumengine.Category')),
            ],
        ),
    ]
