# Generated by Django 2.1.3 on 2018-11-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumengine', '0010_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
