# Generated by Django 2.1.3 on 2018-11-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumengine', '0011_auto_20181121_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('date_of_pub', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumengine.ForumUser')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumengine.Topic')),
            ],
        ),
    ]
