# Generated by Django 2.1.3 on 2018-11-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumengine', '0013_auto_20181121_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='slug',
            new_name='topic_slug',
        ),
    ]
