# Generated by Django 2.1.3 on 2018-11-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumengine', '0015_auto_20181121_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_slug',
            new_name='slug',
        ),
    ]
