# Generated by Django 2.1.3 on 2018-11-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumengine', '0017_auto_20181121_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('date_of_pub', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumengine.ForumUser')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='unnamed', max_length=80)),
                ('date_of_pub', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumengine.ForumUser')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumengine.Category')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumengine.Topic'),
        ),
    ]
