# Generated by Django 2.1.3 on 2018-11-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumengine', '0018_auto_20181121_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voted_users',
            field=models.ManyToManyField(blank=True, default=None, related_name='voted_users', to='forumengine.ForumUser'),
        ),
    ]
